### ISSUE TITLE
OCR?

### ISSUE THREAD

**Issue by bef55** [fedelemantuano/tika-app-python#1]
Tika as a standalone will OCR an image.  Is there a way to access that functionality through your code?  Thanks very much.

**Comment by fedelemantuano** [comment]
@bef55 maybe yes. Can you give me more details?
Are you talking about [it](https://wiki.apache.org/tika/TikaOCR)?

**Comment by bef55** [comment]
Yes, @fedelemantuano that is what I am talking about.  I am trying to grab text from images such as gif, tif, jpg, png and so on.  Any advice on how to access that functionality via your code would be very well appreciated.

**Comment by bef55** [comment]
@fedelemantuano Actually, I have been doing some additional testing, and it appears that your code already does perform OCR on images.  So this issue should be closed.  Thanks very much.

**Comment by fedelemantuano** [comment]
Hi @bef55 did you pass image file and the output has the text on it?

**Comment by bef55** [comment]
Yes.

**Comment by fedelemantuano** [comment]
Thanks a lot
