### ISSUE TITLE
how i can extract images from images

### ISSUE THREAD

**Issue by zainali95** [fedelemantuano/tika-app-python#4]
what i am looking for is to display images in a doc with apache tika wrapper

**Comment by fedelemantuano** [comment]
Can you explain it better? This is a wrapper of Apache Tika and maybe you can see its documentation.

**Comment by zainali95** [comment]
yes, it is a wrapper of Apache Tika, In this wrapper, we can get the image tag with XML tags in place but not the image itself. I want to get the image as well because tika is capable of extracting images as well 
https://www.tutorialspoint.com/tika/tika_metadata_extraction.htm

**Comment by fedelemantuano** [comment]
Can you send me a PR, that I can see? Or can you send me the command line options (if exist) that solve your problem?

**Comment by fedelemantuano** [comment]
I will reopen this issue if I have more data.
