### ISSUE TITLE
Messed order of parsed texts

### ISSUE THREAD

**Issue by luke4u** [fedelemantuano/tika-app-python#6]
Hi Guys,

The bulk paragraphs are wrongly placed at the bottom of the parsed texts. Is there any configuration to correct the order? Found sth [here](http://novyden.blogspot.com/2011/06/extracting-text-from-pdf-files-with.html), but not sure if this can be implemented here?

Thanks so much. Luke

_Input Pdf file left and output text right shown in screenshot below:_

![68594595-cb8be980-048f-11ea-8a27-d2fba6fc2471](https://user-images.githubusercontent.com/45267576/68955387-d14e3b80-07bd-11ea-85fb-0b7c3570386a.png)

**Comment by yourbrainon4n6** [comment]
@luke4u why did you close this? Just curious.
